language: node_js

node_js:
  - '7'

env:
  global:
    - TRAVIS_GH_REPO_SLUG: kamataryo/extypes

cache:
  yarn: true
  directories:
    - "~/.cache/yarn"

before_script:
  - "npm run build:prod"
  - "yarn global add codecov"

script:
  - "npm run lint"
  # send coverage
  - "npm run coverage"
  - "codecov"

after_success:
  # package auto update pull request
  - "openssl aes-256-cbc -K $encrypted_97f1f67cd4d6_key -iv $encrypted_97f1f67cd4d6_iv -in .travis_ecdsa.enc -out ./.travis_ecdsa -d"
  - "mv ./.travis_ecdsa $HOME/.ssh/id_ecdsa && chmod 600 $HOME/.ssh/id_ecdsa"
  - "./bin/travis-cron-upgrade.sh"
  # prepare for publish
  - "cp -r ./dist/* ./"

deploy:
  provider: npm
  email: "kamataryo@users.noreply.github.com"
  on:
    tags: true
  skip_cleanup: true
  api_key:
    secure: Bt5fcUdz3Tenk+5nazbbvqnVgkYbiEm98TWE7Krt+vLdKHFBK6ACQrGc0JipYE1V+0jarei10SMZUqINWgb5OLhudHMC4QlAHv9mlKabBvNqCaSklIYx73pjGkWgc3ojzBwe3cYstMR4EFaa4VxILn+Iidz/GGyFcHoQ5AeYtX/CF0QOlTtrekdKjGW+Tp/xoTgJiAzstK1I13ijToFYyRT2U/jtPnS9q9sDS4RaKuLKzSWzR7VONlUo8jEdofTPumxA5qM8KAZoP1SjGXKvWDSztQsGReGckdgMlUaytXV/6UcT8t9S61uVHvZdksWhWut6CPjB07BFCno/Ca7qrtDgKjvK4+B0u6G+TVQtRmg+OxVApRGqfWIQdZEVXfzz6KvtK1L7+PlLbZWSb4hR9At2M/57IA8wHFHU1r0FZWjSgtA8b46G5yUnw1v2B/C+1qvP80AXQEjL3nHDXFlOomBicVVZnt0AUXQ4j8RfBpMKdsuVAydkaOH+tOtRXSuOgYpQechOgDIkitFR5q0Bhk7n+fBja5RHX5TrOPB+0/4FSQc3pfp7eSuC6xdOVFQP4KJpdgdbS9BxH+F1BHUsLF5o9fVRoQSQMA162Agt+bFXN90DLl6xMDeTYVg34YEUU0jAipkSDvCsmurfu95iURwb/3UBmQJ3nXk/gDxXG9A=
