sudo: false

language: node_js

node_js:
  - '8'

env:
  global:
    - GH_REF: kamataryo/extypes

cache:
  yarn: true
  directories:
    - "~/.cache/yarn"

before_script:
  - "npm run build"
  - "yarn global add codecov"

script:
  - "npm run lint"
  # send coverage
  - "npm run coverage >/dev/null 2>&1"
  - "codecov"

after_success:
  # prepare GitHub deploy keys
  - "openssl aes-256-cbc -K $encrypted_97f1f67cd4d6_key -iv $encrypted_97f1f67cd4d6_iv -in .travis_ecdsa.enc -out ./.travis_ecdsa -d"
  - "mv ./.travis_ecdsa $HOME/.ssh/id_ecdsa && chmod 600 $HOME/.ssh/id_ecdsa"
  # package upgrade
  - ./.bin/travis-cron-upgrade.sh

before_deploy:
  # rebuild repository to enable partial import, such as `import '@kamataryo/extypes/Array/$random'`
  - '[[ $TRAVIS_TAG != "" ]] && babel ./src --out-dir ./'

deploy:
  provider: npm
  email: "kamataryo@users.noreply.github.com"
  on:
    tags: true
  skip_cleanup: true
  api_key:
    secure: Bt5fcUdz3Tenk+5nazbbvqnVgkYbiEm98TWE7Krt+vLdKHFBK6ACQrGc0JipYE1V+0jarei10SMZUqINWgb5OLhudHMC4QlAHv9mlKabBvNqCaSklIYx73pjGkWgc3ojzBwe3cYstMR4EFaa4VxILn+Iidz/GGyFcHoQ5AeYtX/CF0QOlTtrekdKjGW+Tp/xoTgJiAzstK1I13ijToFYyRT2U/jtPnS9q9sDS4RaKuLKzSWzR7VONlUo8jEdofTPumxA5qM8KAZoP1SjGXKvWDSztQsGReGckdgMlUaytXV/6UcT8t9S61uVHvZdksWhWut6CPjB07BFCno/Ca7qrtDgKjvK4+B0u6G+TVQtRmg+OxVApRGqfWIQdZEVXfzz6KvtK1L7+PlLbZWSb4hR9At2M/57IA8wHFHU1r0FZWjSgtA8b46G5yUnw1v2B/C+1qvP80AXQEjL3nHDXFlOomBicVVZnt0AUXQ4j8RfBpMKdsuVAydkaOH+tOtRXSuOgYpQechOgDIkitFR5q0Bhk7n+fBja5RHX5TrOPB+0/4FSQc3pfp7eSuC6xdOVFQP4KJpdgdbS9BxH+F1BHUsLF5o9fVRoQSQMA162Agt+bFXN90DLl6xMDeTYVg34YEUU0jAipkSDvCsmurfu95iURwb/3UBmQJ3nXk/gDxXG9A=

notifications:
  slack:
    secure: "ZHLr/IP2thJ/6mz5fA2UApbYrnQPOHu+lIyIXVGX3laVjz2UcNRtGOnhUcyLcWnle4LrMSIefUNlyRdgImqeNQben+E3DvaUrpoikR0WPHfDpva6PUGIEoyQ15+1jBA5xss2A+hDHLVLlxPLmjvgyLqGcTBIuFDay2NFdBXkQdcHjjPKvG6h57L/r5NMQ6UWaDx3y0U/Dh3hVtU5BPJVaONoVbcRK6C+GtgpiDlvTUGEaVWDnata2RRqOzvmZioLV4RPbWyAMbb6Hq5JN5Ql8m37qxwiyH2j62zIRvOVyBMoJFch4Pq8V/bbEMkUXtFCkVIgyR2/HREHy1CA0Hg/xsDk1XF5akEUDWPLs5elN6E1vVCC+iJ36OPCSMxv4HIN3ZW9SM5cilsexyc71kezIduqCvRJE7w61yGgkgrvYYCjoBjAH1uCyFIkmu8mWhcU9WnrHy+FpSsGcKSBe9ORsH/UlDTEvqeEI9zG6W9EeRomyjrdpY4gLcLDNVdePz+CI66J/tPfauNKfUPoxBGt8EBHTo9S99ivkNdPgwmGydDOJItWuYU4kX1Qoev41bhZH2zl4m6OycWLN4hjNM20iS33g9gCP+f40cwTvOjlg6FxXI+gLnnqe6jCYZ1jRYm8hwuMe1n2xlYqtGWO+CQbJy+g3WgXrmAR2KiaRn+ULaE="
